language: bash

sudo: required

services:
- docker

before_install:
- echo "github dizin listesi aliniyor"
- ls -a
- echo "docker build ediliyor"
- docker build -t "aykutozkan/alpine-tomcat:8.5.50" .
- echo "docker images listesi aliniyor"
- docker images
- echo "docker container listesi aliniyor"
- docker ps -a

script:
- echo "script tag calistirildi"