language: bash

sudo: required

services:
- docker

before_install:
- echo "github dizin listesi aliniyor"
- ls -a
- echo "docker build ediliyor"
- docker build -t "aykutozkan/alpine-tomcat:8.5.50" .
- echo "docker images listesi aliniyor"
- docker images
- docker run -d --name alpine-tomcat-demo-01 -p 80:8080 aykutozkan/alpine-tomcat:8.5.50
- echo "docker container listesi aliniyor"
- docker ps -a


script:
- docker exec -it alpine-tomcat-demo-01 /bin/sh
- ls -a
- pwd